### ISSUE TITLE
BeeRef after the latest update can't run

### ISSUE THREAD

**Issue by Deevad** [flathub/org.beeref.BeeRef#62]
My O.S. Debian KDE
Flatpak 1.14.4
BeeRef , org.beeref.BeeRef , 0.3.3, stable, system

### Install info & recent commit:
```
$ flatpak remote-info --log flathub org.beeref.BeeRef

        ID: org.beeref.BeeRef
       Ref: app/org.beeref.BeeRef/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 72.8 MB
 Installed: 113.0 MB
   Runtime: org.kde.Platform/x86_64/6.4
       Sdk: org.kde.Sdk/x86_64/6.4

    Commit: b1b587a7e05a163bffc3658583e2105f1b30dffedc8be7db08e37f06e42e1428
    Parent: a6ffa9a41fc4a46161e4de2c75aa3a20e0717895be1b979359b61239c7ac5923
   Subject: Automatically merge Flathub bot PRs (af311b4b)
      Date: 2024-05-23 21:44:44 +0000
   History: 

    Commit: a6ffa9a41fc4a46161e4de2c75aa3a20e0717895be1b979359b61239c7ac5923
   Subject: appdata: Fix screenshot-no-media error (cc67a23c)
      Date: 2024-05-23 20:57:41 +0000
```

### Feedback in terminal:

```
$ flatpak run org.beeref.BeeRef
Traceback (most recent call last):
  File "beeref/__main__.py", line 30, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "beeref/view.py", line 28, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "beeref/fileio/__init__.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "beeref/fileio/image.py", line 25, in <module>
ModuleNotFoundError: No module named 'lxml'
[3] Failed to execute script '__main__' due to unhandled exception!
/usr/lib/systemd/system-sleep »»» 

```

### Workaround

Rolling back the recent commit fixes the issue and I can use Beeref again. The command line:
```
sudo flatpak update --commit=938e64eca597b375b484a15b2b6f5f24de715215b077fe3527fa359f92b213f4 org.beeref.BeeRef
```
Detail of the commit I rolled back:
```
    Commit: 938e64eca597b375b484a15b2b6f5f24de715215b077fe3527fa359f92b213f4
   Subject: Update beeref.git to 0.3.1 (52e2660e)
      Date: 2023-12-11 00:50:02 +0000
```
To keep using this version for now , I'll pin (mask) this version. It will prevent my update system to auto update Beeref to the problematic latest release.

```
$ sudo flatpak mask org.beeref.BeeRef
```

**Comment by dginovker** [comment]
Thanks for the issue report, making a PR now that should fix it

**Comment by dginovker** [comment]
Lmk if there's any other issues

**Comment by Deevad** [comment]
Thank you for the super quick fix! :+1: 

I confirm, everything is now working correctly on commit `Commit: bf5b74f9f261c4e25137cb8ed0f99f6050625352eadf53a9bc5b2158965be02f , Update KDE runtime`after a:

```
sudo flatpak mask --remove org.beeref.BeeRef
sudo flatpak update org.beeref.BeeRef
```
_(I write the steps in case someone followed my 'workaround' of reverting and masking)_
